export const SEARCH_RECIPE_NAME_BEGIN = "SEARCH_RECIPE_NAME_BEGIN";
export const SEARCH_RECIPE_NAME_SUCCESS = "SEARCH_RECIPE_NAME_SUCCESS";
export const SEARCH_RECIPE_NAME_ERROR = "SEARCH_RECIPE_NAME_ERROR";

export const SEARCH_INGREDIENTS_BEGIN = "SEARCH_INGREDIENTS_BEGIN";
export const SEARCH_INGREDIENTS_SUCCESS = "SEARCH_INGREDIENTS_SUCCESS";
export const SEARCH_INGREDIENTS_ERROR = "SEARCH_INGREDIENTS_ERROR";

export const GET_SINGLE_RECIPE_BEGIN = "GET_SINGLE_RECIPE_BEGIN";
export const GET_SINGLE_RECIPE_SUCCESS = "GET_SINGLE_RECIPE_SUCCESS";
export const GET_SINGLE_RECIPE_ERROR = "GET_SINGLE_RECIPE_ERROR";

export const CREATE_RECIPE_BEGIN = "CREATE_RECIPE_BEGIN";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_ERROR = "CREATE_RECIPE_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const LOAD_USER_TOKEN = "LOAD_USER_TOKEN";

export const GET_ALL_RECIPES_BEGIN = "GET_ALL_RECIPES_BEGIN";
export const GET_ALL_RECIPES_SUCCESS = "GET_ALL_RECIPES_SUCCESS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_USER_FAVORITES = "GET_USER_FAVORITES";

export const ADD_TO_USER_FAVORITES = "ADD_TO_USER_FAVORITES";

export const LOGOUT_USER = "LOGOUT_USER";

export const RESET_PAGE = "RESET_PAGE";

export const CHANGE_LIMIT = "CHANGE_LIMIT";

export const GET_PERSONAL_BEGIN = "GET_PERSONAL_BEGIN";
export const GET_PERSONAL_SUCCESS = "GET_PERSONAL_SUCCESS";

export const SET_EDIT_RECIPE = "SET_EDIT_RECIPE";

export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_BEGIN = "UPDATE_RECIPE_BEGIN";
export const UPDATE_RECIPE_ERROR = "UPDATE_RECIPE_ERROR";

export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_BEGIN = "DELETE_RECIPE_BEGIN";
export const DELETE_RECIPE_ERROR = "DELETE_RECIPE_ERROR";

export const SET_RECIPE_IMAGE_SUCCESS = "SET_RECIPE_IMAGE_SUCCESS";
