export const FAVORITE_RECIPE = "FAVORITE_RECIPE";
export const SEARCH_RECIPES_BEGIN = "SEARCH_RECIPES_BEGIN";
export const SEARCH_RECIPES_SUCCESS = "SEARCH_RECIPES_SUCCESS";
export const SEARCH_RECIPES_ERROR = "SEARCH_RECIPES_ERROR";
export const GET_FAVORITES_BEGIN = "GET_FAVORITES_BEGIN";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_ERROR = "GET_FAVORITES_ERROR";
export const GET_SINGLE_RECIPE_BEGIN = "GET_SINGLE_RECIPE_BEGIN";
export const GET_SINGLE_RECIPE_SUCCESS = "GET_SINGLE_RECIPE_SUCCESS";
export const GET_SINGLE_RECIPE_ERROR = "GET_SINGLE_RECIPE_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";
